### ISSUE TITLE
Enhance CI config

### ISSUE THREAD

**Issue by inf2381** [corona-warn-app/cwa-app-ios#370]
## Current Implementation
Currently, we enabled "Only build pull requests" in CircleCI which limits, what we can do with the CI tool.

## Suggested Enhancement
I started to create a config that should build on every commit, run the tests + sonarscan on pull requests and grab screenshots only on master but I didn't manage to make it a valid config, yet:

```yaml
version: 2.1

jobs:
  build:
    macos:
      xcode: 11.5.0
    shell: zsh

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: brew install swiftlint && cd src/xcode && bundle install
      - run:
          name: Build
          command: cd src/xcode && bundle exec fastlane build
  test:
    macos:
      xcode: 11.5.0
    shell: zsh
    steps:
      - run:
          name: Tests
          command: cd src/xcode && bundle exec fastlane test
      - run:
          name: Convert coverage information to SonarCloud format
          command: |
            ./scripts/xcov_to_sonarqube_generic.sh src/xcode/fastlane/test_output/*.xccovarchive/ > src/xcode/fastlane/test_output/coverage.xml
            sed -i "" 's|/Users/distiller/project/||' src/xcode/fastlane/test_output/coverage.xml
      - run:
          name: Fix SwiftLint output for SonarCloud
          command: |
                mv src/xcode/swiftlint.result.json src/xcode/swiftlint.result.original.json
                cat src/xcode/swiftlint.result.original.json | jq '.["issues"]' > src/xcode/swiftlint.result.json
      - sonarcloud/scan:
          os: macosx
          version: 4.3.0.2102
      - store_test_results:
          path: src/xcode/fastlane/test_output
      - store_artifacts:
          path: src/xcode/fastlane/test_output
      - store_artifacts:
          path: src/xcode/swiftlint.result.json

  grab-screenshots:
    macos:
      xcode: 11.5.0
    steps:
      - checkout
      - run: cd src/xcode && bundle install
      - run:
          name: Snapshots
          command: cd src/xcode && bundle exec fastlane snapshot
      - store_artifacts:
          path: src/xcode/screenshots

orbs:
  sonarcloud: tkowark/sonarcloud3@0.1.0
workflows:
    # Run everytime
    default:
      jobs:
        - build
    # Run only on pull requests
    pull_request:
      jobs:
        - test:
            context: SonarCloud
    # Run only on master
    release:
      jobs:
        - grab-screenshots:
          filters:
            branches:
              only:
                - master
```

Once this config is working, we can disable the "Only build pull requests" on CircleCI.

I started this task in #350 but got stuck.
